### ISSUE TITLE
Frage: CronJob

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#10]
Hi,

kleine Frage was passiert wenn ein Cronjob mal nicht lauft bzw der Server gerade zu einem Spiel nicht online war.

Wird da was nachgeholt oder ist das dann futsch?

**Comment by MarkusHiller** [comment]
Spiele kannst du im Kontrollzentrum nachholen lassen. Die Spiele finden
dann ein oder zwei Tage später statt.

Am 31.08.2016 12:20 schrieb "bornhaeusser" notifications@github.com:

**Comment by bornhaeusser** [comment]
Ok, danke für die Info.
