### ISSUE TITLE
Erweiterung: Taktik Umstellung

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#11]
Evtl. ist es möglich eine 15min Halbzeitpause einzuführen in dieser es gestattet ist Taktische Änderungen durchzuführen als Anpassung bzw Erweiterung mit aufzunehmen.

**Comment by MarkusHiller** [comment]
Auch wenn ich das Spiel erst vor kurzem übernommen habe, möchte ich dem
alten gedanken treu bleiben. Es soll ein Manager sein den man mit wenig
zeitaufwand und für alle fair spielen kann. Da man nicht garantieren kann
das beide Spieler in dieser Halbzeit online sein können, sollten keine
Spiel verändernden Maßnahmen möglich sein.

Dieses Feature wird also nicht kommen.

Wenn ihr es bei euch wollt, könnt ihr es gerne bei euch implementieren.

Liebe Grüße

Am 31.08.2016 15:02 schrieb "bornhaeusser" notifications@github.com:

**Comment by bornhaeusser** [comment]
Erstmal finden wir es mega super klasse das das Spiel weiter entwickelt wird. Wir sind ein kleines Team ITler (leider keiner Programmierer :-) ) Pfriemeln unsere Gedanken zusammen und wälzen uns durch den Code ohne php knowhow :+1:  .....

Wenn wir genau wissen wohin die Reise gehen soll können wir unsere Gedanken bündeln. Wir haben rießen Spaß an dem Spiel und freuen uns wenn wir dazu betragen können um es nach vorne zu bringen.

Nochmal großen Kompliment von uns das du das weiter machst!!!

Grüße aus Karlsruhe
