### ISSUE TITLE
Forum / Archiv ohne Funktion 

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#14]
Das Archiv/Forum ist für Admins und Helfer ohne Funktion. 
Man kann keinerlei Einträge tätigen.

**Comment by MarkusHiller** [comment]
Ja das ist richtif. Das Forum wurde schon vor langer Zeit abgeschaltet und
wurde zum nachlesen als archiv gekennzeichnet.
Es gibt noch weitere Altlasten. Ich werde diese in einem Cleanup entfernen.

Am 04.09.2016 19:26 schrieb "bornhaeusser" notifications@github.com:
