### ISSUE TITLE
Frage zu Moral

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#15]
Wiso ist bei PS +1,8 Punkte Moral (Wiso nicht 2) mir erschließt sich nicht warum man den Wert mit +1,8 setzt)

**Comment by MarkusHiller** [comment]
Da ich selbst das System nicht entwickelt habe, kann ich auch hier nur mutmaßen.

Der Grund wird sicher sein, dass der Spieler mehr als einmal alle zwei Tage eingesetzt werden muss. Jeder spieler verliert ja pro Tag 1% Moral, dass wären bei zwei Tagen 2%. würde der Spieler pro Einsatz 2% gewinnen müsste man diesen nur jeden zweiten Tag spielen lassen um auf +/- 0% zu kommen. setzt man ihn aber bei 1,8% nur alle zwei Tage einmal ein so verliert er 0,2% in zwei Tagen.

Ich könnte mir vorstellen das dies gemacht wurde, damit die reicheren Nutzer nicht die ganzen Spieler behalten, aber nur zu Testspielen einsetzen. Man muss dadurch meiner Meinung nach etwas mehr auf seine Spieler achten.

Im Hinblick auf die Zukunft wird dieses System sicher nochmal überarbeitet. Ich habe mir da schon gedanken zu gemacht, was auch die Moral abhängig von Gewinnen und Verlieren macht.

Aber auch hierzu muss erst das Simulationsscript angepasst werden. Für euch als eigenständiger Server wird es dann auch eine einfache Möglichkeit geben, diese Werte anzupassen.

**Comment by bornhaeusser** [comment]
Klingt vielversprechend :+1: 
Thx
