### ISSUE TITLE
Freie Spieler zu wenige

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#17]
Es gibt das Problem daß das Auffüllen der Teams nicht ganz funktioniert. Wir sehen das wir zu wenige freie Spieler haben - wo und wann werden diese generiert?

**Comment by MarkusHiller** [comment]
Es gibt zum Spieler generieren eigentlich nur das aa_spieler_erzeugen.php
Script. Dieses generiert aber nur an den Tagen wo Jugendspieler zum Team
kommen pro Team ein neuen Spieler. Es sollte eigentlich auch genug frei
Spieler geben. Sollte dies nicht der Fall sein, kann ich gerne für den
Adminbereich ein entsprechendes Spieler generieren Script bauen, wo Ihr
sagen könnt jetzt 100 neue Spieler generieren.

Wäre das gewünscht?

2016-09-26 16:20 GMT+02:00 bornhaeusser notifications@github.com:

**Comment by bornhaeusser** [comment]
kling sehr gut :-)

**Comment by MarkusHiller** [comment]
Hey, 

einige eurer Cronjobs laufen nicht richtig. Das wird auch der Grund sein, dass ihr sowenig Spieler in der Datenbank habt.

Ich hab das gerade mal bei euch geprüft und die Computer teams werden z.b. nicht gemanaged

**Comment by bornhaeusser** [comment]
mmmh..... kann ich das checken welche Probleme machen?

**Comment by MarkusHiller** [comment]
Du kannst dir normalerweise nen Fehlerbericht senden lassen, wenn der
cronjob fehlschlägt.

Ich vermute aber, dass es wieder was mit dem Pfad zutun hatte und es jetzt
läuft.

Schau morgen einfachmal in ein Computerteam wann es das letztemal gemanaged
wurde. Steht hinter dem Trainer in klammern.

Am 29.09.2016 21:02 schrieb "bornhaeusser" notifications@github.com:

**Comment by bornhaeusser** [comment]
Danke für den Hinweis!!!!!

**Comment by MarkusHiller** [comment]
Closed with https://github.com/MarkusHiller/OpenSoccer/commit/dc986c095917eb8def1c149b795f93d3208522a7
