### ISSUE TITLE
SupportController.php

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#18]
geht bei mir nur mit der Class:

`class SupportController {

```
public static function getUnreadedTicketCount($userIds, $status) {
    $supportSql = $status == 'Helfer' || $status == 'Admin' ? "" : " AND visibilityLevel = 0";
    $sql = "SELECT COUNT(*) FROM " . CONFIG_TABLE_PREFIX . "supportRequests WHERE open = 1 AND '" . $userIds . "' NOT IN (SELECT userId FROM " . CONFIG_TABLE_PREFIX . "supportRead WHERE anfrageID = id)" . $supportSql;
    $result = DB::query($sql, FALSE);

    return mysql_result($result, 0);
}
```

}`

**Comment by MarkusHiller** [comment]
Was geht bzw. geht nicht?

**Comment by bornhaeusser** [comment]
<img width="677" alt="bildschirmfoto 2016-09-29 um 19 23 18" src="https://cloud.githubusercontent.com/assets/6609040/18964678/32a9d0ec-867a-11e6-868e-d32c102402b6.png">

**Comment by MarkusHiller** [comment]
Du hast vermutlich diesen Commit übersehen:
https://github.com/MarkusHiller/OpenSoccer/commit/f34ee8a460c602e9bc64f3d66df6638d3ef0b542

Hier wirst du gebeten deine Datenbank-Struktur anzupassen (siehe Structur.sql). Bitte schau in die Beschreibung und berichte nochmal nach dem Update.

**Comment by bornhaeusser** [comment]
wurde nicht vergessen:

<img width="899" alt="bildschirmfoto 2016-09-29 um 19 32 54" src="https://cloud.githubusercontent.com/assets/6609040/18964993/948acc16-867b-11e6-9364-d7736d4919ed.png">

**Comment by bornhaeusser** [comment]
kann auch ausgewählt werden:

<img width="847" alt="bildschirmfoto 2016-09-29 um 19 34 44" src="https://cloud.githubusercontent.com/assets/6609040/18965053/d2f71cfc-867b-11e6-9426-cf002ab1b67e.png">

**Comment by MarkusHiller** [comment]
Sollte mit https://github.com/MarkusHiller/OpenSoccer/commit/7860a2339de71d803a4a17dd86f095dd2723b92d behoben sein.

Linux achtet bei den Tabellennamen auf Groß- und Kleinschreibung

**Comment by MarkusHiller** [comment]
Ach du hast ja sogar die Lösung oben geschrieben. Jetzt verstehe ich diese auch ;)
