### ISSUE TITLE
Aufstellung

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#19]
Die Namen bei der Aufstellungen fehlen. 
Nach Farben aufstellen wurde auch entfernt?!

**Comment by bornhaeusser** [comment]
RN passen auch noch nicht.

<img width="297" alt="bildschirmfoto 2016-09-29 um 18 34 47" src="https://cloud.githubusercontent.com/assets/6609040/18963016/724be67e-8673-11e6-8779-ed46f15405a3.png">

**Comment by MarkusHiller** [comment]
Namen wurden erstmal wieder entfernt, da es zu problemen beim auswählen kam.

Aufstellen nach Farbe wurde entfernt und wird später durch ein Vorlagensystem ersetzt.

Die RN sollten noch garnicht dabei sein, die habe ich leider beim updaten der Pfade mit commited.
