### ISSUE TITLE
Cub Spiele

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#20]
bei uns ist im Kontrollzentrum folgendes aufgetaucht.....

<img width="486" alt="bildschirmfoto 2016-10-02 um 09 13 47" src="https://cloud.githubusercontent.com/assets/6609040/19019241/a80cb0cc-8880-11e6-9519-f3dc0666e583.png">

**Comment by MarkusHiller** [comment]
Jupp ist bekannt. Die Cup-Spiele einer Liga strikten am Anfang der Saison. Einfach auf nachholen klicken und dann läuft der Cup normal weiter. Ich schaue mir das bei Gelegenheit mal an.

**Comment by MarkusHiller** [comment]
Fixen with commit 4679677e691b4cafbfe95fe936f2503ca59a2247
