### ISSUE TITLE
team.php Anzeige Trophäe Manager der saison fehlt

### ISSUE THREAD

**Issue by warover** [MarkusHiller/OpenSoccer#22]
MDS-Trophäe wird nicht angezeigt wenn mds die einzige ist
-if ($sql3['meisterschaften'] > 0 OR $sql3['pokalsiege'] > 0 OR $sql3['cupsiege'] > 0) {
+if ($sql3['meisterschaften'] > 0 OR $sql3['pokalsiege'] > 0 OR $sql3['cupsiege'] > 0 OR $mdsSiege4 > 0) {

**Comment by MarkusHiller** [comment]
fixed with https://github.com/MarkusHiller/OpenSoccer/commit/6dc3ba83458fcd856e331393b86e2f439d2c2c72
