### ISSUE TITLE
Stadionausbau

### ISSUE THREAD

**Issue by bornhaeusser** [MarkusHiller/OpenSoccer#7]
Der erste Stadionausbau wird direkt gebaut. Man hat keine Bauzeit. 
Geklickt, Gekauft, sofort Ausgebaut.

**Comment by MarkusHiller** [comment]
Das ist korrekt so, nach aktuellem Stand. Eine zweite Erweiterung ist dann aber erst mögliche, wenn die die erste abgeschlossen ist.

Aber ja die Plätze sind dann sofort verfügbar.

**Comment by warover** [comment]
eine bauzeit von ca. 5-15 tagen wäre sinnvoll je nach erweiterungsgröße, das bierzelt dauert ja auch etwa solange zu bauen :-))
