### ISSUE TITLE
wrong player position order T>S>M>A

### ISSUE THREAD

**Issue by warover** [MarkusHiller/OpenSoccer#8]
thx for forking this project!
one small fix suggestion:

in aufstellung.php team.php kader.php and aa_spieltag_simulation.php
ORDER BY position='S', position='M', position='A', position='T', staerke DESC";
instead of order by position DESC, staerke DESC
so that player are ordered to positions T > A > M > S

**Comment by MarkusHiller** [comment]
Fixed with commit https://github.com/MarkusHiller/OpenSoccer/commit/f0c569b160926e29962acb8247f34fe3ecd01c1b
